#!/bin/bash

python3 reboundtttrbatch.py strict 11 &
python3 reboundtttrbatch.py 0 11 &
python3 reboundtttrbatch.py 1 11 &
python3 reboundtttrbatch.py 2 11 &
python3 reboundtttrbatch.py 3 11 &
python3 reboundtttrbatch.py 4 11 &
python3 reboundtttrbatch.py 5 11 &
python3 reboundtttrbatch.py 6 11 &
python3 reboundtttrbatch.py 7 11 &
python3 reboundtttrbatch.py 8 11 &
python3 reboundtttrbatch.py 9 11

