#!/bin/bash

#SBATCH -J SimAU_July30
#SBATCH -p general
#SBATCH -o SimAU_July30_%j.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taylor11@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=96:00:00
#SBATCH --mem=128G

export XDG_RUNTIME_DIR=/N/slate/taylor11/xdg_dir

for i in {0..161..1}
do
	python3 simAU.py $i &
done
python3 simAU.py 162
python3 massListSorter.py Masslists/2000SimAUJuly30

date
