#!/bin/bash

#SBATCH -J SIMAU_July27
#SBATCH -p general
#SBATCH -o SIMAU_July27_%j.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taylor11@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=96:00:00
#SBATCH --mem=64G

export XDG_RUNTIME_DIR=/N/slate/taylor11/xdg_dir

for i in {1..162..1} #162 times, not 163
do
	python3 simAU.py &
	sleep .2
done
python3 simAU.py #163rd time does not include a '&' nor a 'sleep' command

date
