#!/bin/bash

#SBATCH -J SimAU_aug4_0_22
#SBATCH -p general
#SBATCH -o SimAU_aug4_0_22_%j.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taylor11@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=96:00:00
#SBATCH --mem=128G

python3 massListSorter.py 10
sleep 5
for i in {0..21}
do
	python3 simAUBatch.py $i &
	sleep 2
done
sleep 5
python3 simAUBatch.py 22
sleep 5
python3 massListSorter.py 10 Masslists/JupiterSimAUaug4Batch

date
