#!/bin/bash

#SBATCH -J SimAU_aug3
#SBATCH -p general
#SBATCH -o SimAU_aug3_%j.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taylor11@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=96:00:00
#SBATCH --mem=200G

python3 massListSorter.py 2
sleep 5
for i in {0..161}
do
	python3 simAUBatch.py $i &
	sleep 2
done
sleep 5
python3 simAUBatch.py 162
sleep 5
python3 massListSorter.py 2 Masslists/JupiterSimAUaug3Batch

date
