#!/bin/bash

#SBATCH -J SimAU_aug5_63
#SBATCH -p general
#SBATCH -o SimAU_aug5_63_%j.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taylor11@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=3
#SBATCH --time=36:00:00
#SBATCH --mem=64G

python3 massListSorter.py 263reds
sleep 5
python3 simAUBatch.py 63
sleep 5
wait
python3 massListSorter.py 263reds Masslists/JupiterSimAUaug5Batch

date